#spring:
#  jpa:
#    database: MYSQL
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/notedb
#    username: root
#    password: 9304083096s
#    driverClassName: com.mysql.jdbc.Driver
#
#  server:
#    port: 8080
#
#
#spring.data.mongodb.authentication-database=admin
#spring.data.mongodb.uri=mongodb://172.23.239.155:27017/moviedb
#spring.data.mongodb.port=27017

spring:
  application:
    name: movie-server

  cloud:
    config:
      uri: https://localhost:8889

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka
  register-with-eureka: true
  fetchRegistry: true

server:
  port: 9091


